In [1]:
import pandas as pd

In [6]:
df1[['texts','sentiment_polar']]

                                                  texts  sentiment_polar
0     徐州之前刚因为铁链女出大风头，好不容易大家忘了点。结果又开始蹭徐州才是淄博烧烤发源地热度，b...         0.125605
1                              不好意思对徐州的印象只有八孩铁链女和拐卖妇女           0.016171
2                                  徐州只能让我想起一件事情，铁链女🙈🙉🙊          0.007867
3                                             铁链女，丰县八孩          0.927534
4                                            想知道这个女的后续          0.885835
...                                                 ...              ...
6689                      强奸犯不是扬某侠的家人，强奸生下的不是“人”是被强奸的恶果         0.000990
6690  如果这事调查不力，让人贩子兼强奸犯逍遥法外，不能保护好“她”，只能说明我们中国政府大力支持人...         0.016905
6691                                  越烂的基因越是拼命想着要延续下去。         0.011656
6692  怎么我们女生好欺负吗？就这样谁敢出门，男女平等？？女生在社会上是弱势群体，不应该得到政府，男...         0.999905
6693  生前遗物怎么进行DNA比对？ 家长让14岁的桑某妞领着18岁的小花梅找个好人家，然后14岁的...         0.999608

[6694 rows x 2 columns]

In [7]:
df2 = pd.read_csv('df_baidu.csv')
df2

                                                  texts  pm      pp      np
0     徐州之前刚因为铁链女出大风头，好不容易大家忘了点。结果又开始蹭徐州才是淄博烧烤发源地热度，b...  负向  0.0069  0.9931
1                              不好意思对徐州的印象只有八孩铁链女和拐卖妇女    负向  0.2115  0.7885
2                                  徐州只能让我想起一件事情，铁链女🙈🙉🙊   负向  0.2986  0.7014
3                                             铁链女，丰县八孩   正向    0.92    0.08
4                                            想知道这个女的后续   正向  0.7359  0.2641
...                                                 ...  ..     ...     ...
6689                      强奸犯不是扬某侠的家人，强奸生下的不是“人”是被强奸的恶果  负向  0.0016  0.9984
6690  如果这事调查不力，让人贩子兼强奸犯逍遥法外，不能保护好“她”，只能说明我们中国政府大力支持人...  负向  0.0002  0.9998
6691                                  越烂的基因越是拼命想着要延续下去。  负向  0.0002  0.9998
6692  怎么我们女生好欺负吗？就这样谁敢出门，男女平等？？女生在社会上是弱势群体，不应该得到政府，男...  负向  0.0003  0.9997
6693  生前遗物怎么进行DNA比对？ 家长让14岁的桑某妞领着18岁的小花梅找个好人家，然后14岁的...  负向  0.0005  0.9995

[6694 rows x 4 columns]

In [8]:
df3 = pd.read_excel('data_emo_classify.xlsx')
df3

,Unnamed: 0,Unnamed: 0.1,comments_count,attitudes_count,reposts_count,created_at,status_city,status_country,status_province,user_id,...,length,positive,negative,anger,disgust,fear,sadness,surprise,good,happy
0,0,0,0,41,0,2023-04-25 13:48:34,济南,中国,山东,5953395370,...,37,1,1,0,1,0,0,0,1,0
1,1,1,1,8,0,2023-04-25 13:48:33,信阳,中国,河南,6046338053,...,9,0,1,0,0,1,0,0,0,0
2,2,2,0,20,0,2023-04-25 13:48:01,中山,中国,广东,6270833313,...,11,0,0,0,0,0,0,0,0,0
3,3,3,1,2,0,2023-04-25 13:44:46,北京,中国,北京,5334170262,...,5,0,0,0,0,0,0,0,0,0
4,4,4,0,2,0,2023-04-25 13:40:10,武汉,中国,湖北,6056043508,...,5,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6689,6689,6689,0,1,0,2022-02-12 13:23:55,NaN,NaN,NaN,6912848963,...,8,0,2,0,2,0,0,0,0,0
6690,6690,6690,0,0,0,2022-02-12 03:42:37,NaN,NaN,NaN,3087874701,...,24,0,3,0,3,0,0,0,0,0
6691,6691,6691,0,1,0,2022-02-12 01:21:25,NaN,NaN,NaN,1985123417,...,5,1,0,0,0,0,0,0,1,0
6692,6692,6692,0,1,0,2022-02-12 01:16:59,NaN,NaN,NaN,6628549450,...,19,1,2,0,2,0,0,0,1,0
6693,6693,6693,0,0,0,2022-02-12 01:11:15,NaN,NaN,NaN,2460468142,...,60,0,2,0,1,0,1,0,0,0

In [9]:
df3.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'comments_count', 'attitudes_count',
       'reposts_count', 'created_at', 'status_city', 'status_country',
       'status_province', 'user_id', 'id', 'isLongText', 'user_screen_name',
       'user_verified', 'user_gender', 'user_follow_count',
       'user_followers_count', 'user_verified_reason', 'weibo_emoji', 'tags',
       'texts', 'length', 'positive', 'negative', 'anger', 'disgust', 'fear',
       'sadness', 'surprise', 'good', 'happy'],
      dtype='object')

In [11]:
df3[['texts','length', 'positive', 'negative', 'anger', 'disgust', 'fear', 'sadness', 'surprise', 'good', 'happy']]

,texts,length,positive,negative,anger,disgust,fear,sadness,surprise,good,happy
0,徐州之前刚因为铁链女出大风头，好不容易大家忘了点。结果又开始蹭徐州才是淄博烧烤发源地热度，b...,37,1,1,0,1,0,0,0,1,0
1,不好意思对徐州的印象只有八孩铁链女和拐卖妇女,9,0,1,0,0,1,0,0,0,0
2,徐州只能让我想起一件事情，铁链女🙈🙉🙊,11,0,0,0,0,0,0,0,0,0
3,铁链女，丰县八孩,5,0,0,0,0,0,0,0,0,0
4,想知道这个女的后续,5,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
6689,强奸犯不是扬某侠的家人，强奸生下的不是“人”是被强奸的恶果,8,0,2,0,2,0,0,0,0,0
6690,如果这事调查不力，让人贩子兼强奸犯逍遥法外，不能保护好“她”，只能说明我们中国政府大力支持人...,24,0,3,0,3,0,0,0,0,0
6691,越烂的基因越是拼命想着要延续下去。,5,1,0,0,0,0,0,0,1,0
6692,怎么我们女生好欺负吗？就这样谁敢出门，男女平等？？女生在社会上是弱势群体，不应该得到政府，男...,19,1,2,0,2,0,0,0,1,0
6693,生前遗物怎么进行DNA比对？ 家长让14岁的桑某妞领着18岁的小花梅找个好人家，然后14岁的...,60,0,2,0,1,0,1,0,0,0

In [12]:
df4 = pd.read_csv('emotion_score.csv')
df4

,texts,words,score
0,徐州之前刚因为铁链女出大风头，好不容易大家忘了点。结果又开始蹭徐州才是淄博烧烤发源地热度，b...,"['徐州', '之前', '刚', '铁链', '女出', '风头', '好不容易', '忘...",0.0
1,不好意思对徐州的印象只有八孩铁链女和拐卖妇女,"['不好意思', '徐州', '印象', '八孩', '铁链', '女', '拐卖妇女', ...",0.0
2,徐州只能让我想起一件事情，铁链女🙈🙉🙊,"['徐州', '只能', '想起', '一件', '事情', '铁链', '女', '🙈',...",0.0
3,铁链女，丰县八孩,"['铁链', '女', '丰县', '八孩', ' ']",0.0
4,想知道这个女的后续,"['想', '知道', '女', '后续', ' ']",0.0
...,...,...,...
6689,强奸犯不是扬某侠的家人，强奸生下的不是“人”是被强奸的恶果,"['强奸犯', '扬', '某侠', '家人', '强奸', '生下', '强奸', '恶果']",-18.0
6690,如果这事调查不力，让人贩子兼强奸犯逍遥法外，不能保护好“她”，只能说明我们中国政府大力支持人...,"['事', '调查', '不力', '人贩子', '兼', '强奸犯', '逍遥法外', '...",-17.0
6691,越烂的基因越是拼命想着要延续下去。,"['越烂', '基因', '拼命', '想着', '延续下去']",0.0
6692,怎么我们女生好欺负吗？就这样谁敢出门，男女平等？？女生在社会上是弱势群体，不应该得到政府，男...,"['怎么', '女生', '欺负', '敢', '出门', '男女平等', '女生', '社...",-3.0
6693,生前遗物怎么进行DNA比对？ 家长让14岁的桑某妞领着18岁的小花梅找个好人家，然后14岁的...,"['生前', '遗物', '怎么', '进行', 'DNA', ' ', '家长', '14...",-13.0